- name: Downloading and installing public signing key
  rpm_key:
    state: present
    key: "{{ gpg_key_logstash }}"

- name: Creeating a repo file for Logstash
  copy:
    src: logstash.repo
    dest: /etc/yum.repos.d/logstash.repo
    owner: root
    group: root
    mode: 0777

- name: Updating repo
  dnf:
    update_cache: yes

- name: Installing Logstash and its dependencies
  dnf:
    name:
      - logstash
    state: latest

- name: Opening port for Logstash
  shell: |
    sudo firewall-cmd --permanent --zone=public --add-port=9600/tcp
    sleep 10
    sudo firewall-cmd --reload
- name: Making sure that logstash is stared and enabled
  service:
    name: logstash
    state: restarted
    enabled: true


